wip

diff --git a/.github/workflows/e2etest-run-tests.yml b/.github/workflows/e2etest-run-tests.yml
--- a/.github/workflows/e2etest-run-tests.yml
+++ b/.github/workflows/e2etest-run-tests.yml
@@ -14,6 +14,11 @@ on:
         description: The name of the target environment
         type: string
         required: true
+      allowedMemoryDelta:
+        description: The allowed memory delta expressed in %, workflow will fail if the the memory usage grows beyond this value
+        type: number
+        default: 10
+        required: false
       cpuThreshold:
         description: The cpu threshold
         type: string
@@ -103,7 +108,13 @@ jobs:
         run: |
           sudo apt install -y osconfig
 
-      - name: Configure OSConfig
+      - name: Capture memory metrics (Start)
+        id: memory-start
+        run: |
+          mem_start=`free | sed -n 2p | cut -c 20-32 | tr -d ' '`
+          echo ::set-output name=mem_start::$mem_start
+
+      - name: Configure and Start OSConfig
         run: |
           sudo systemctl stop osconfig
           sudo sed -i '/\"FullLogging\"/c\\  \"FullLogging\": 1,' /etc/osconfig/osconfig.json
@@ -151,6 +162,22 @@ jobs:
         if: inputs.cpuThreshold != ''
         run: |
           kill -SIGINT `pidof pidstat`
+
+      - name: Stop OSConfig
+        run: |
+          sudo systemctl stop osconfig
+
+      - name: Capture memory metrics (Stop)
+        run: |
+          mem_stop=`free | sed -n 2p | cut -c 20-32 | tr -d ' '`
+          delta=$(bc -l <<< "mem_start=${{ steps.memory-start.outputs.mem_start }};mem_stop=$mem_stop;delta=mem_start/mem_stop;print delta;")
+          echo Memory Start: ${{ steps.memory-start.outputs.mem_start }}, Stop: $mem_stop, Delta: $delta
+          
+          # Check if the delta is greater than defined threshold
+          result=`bc -l <<< "delta=$delta;high=1+(0.${{ inputs.allowedMemoryDelta }});low=1-(0.${{ inputs.allowedMemoryDelta }});if(high > delta && delta > low) print 0 else print 1;"`
+          if [ "$result" == 1 ]; then
+            echo "::error Memory usage has exceeded allowable delta (${{ inputs.allowedMemoryDelta }}%), current delta: $delta" && exit 1
+          fi
 
       - name: Check performance results - Agent
         if: inputs.cpuThreshold != ''
