test

diff --git a/.github/workflows/package-build.yml b/.github/workflows/package-build.yml
--- a/.github/workflows/package-build.yml
+++ b/.github/workflows/package-build.yml
@@ -1,153 +1,229 @@
-name: Build Package
+name: Package Build
+# name: Package
 
 on:
-  workflow_call:
-    inputs:
-      os:
-        description: The list of operating systems to use in the strategy matrix.
-        type: string
-        required: false
-        default: '["ubuntu18.04", "ubuntu20.04", "debian9"]'
-      variant:
-        description: The list of variants to use in the strategy matrix.
-        type: string
-        required: false
-        default: '[{"arch": "arm", "platform": "linux/arm/v7"}, {"arch": "arm64", "platform": "linux/arm64/v8"}, {"arch": "amd64", "platform": "linux/amd64"}]'
-      artifact:
-        description: The artifact to publish.
-        type: string
-        required: false
-        default: 'package'
-      build-type:
-        description: The build type to use.
-        type: string
-        default: Release
-        required: false
-      signed:
-        description: If the packages should be signed. This will create a second artifact for the signed packages (<artifact_name>-signed).
-        type: boolean
-        required: false
-        default: true
+  push:
+  # workflow_call:
+  #   inputs:
+  #     artifact:
+  #       description: The artifact to create containing the packages.
+  #       type: string
+  #       required: false
+  #       default: "package"
+  #     build-type:
+  #       description: The type of build to perform (Debug | Release).
+  #       type: string
+  #       required: false
+  #       default: "Release"
+env:
+  build-type: Release
+  artifact: package
+  threshold: 10
 
 jobs:
-  package:
-    name: Package
+  version:
+    name: Version
     runs-on: ubuntu-latest
+    outputs:
+      tweak: ${{ steps.version.outputs.tweak }}
+    steps:
+      # TODO: get the major, minor, and patch version
+      # REVIEW: why is it hr/min in the tweak ???
+      - name: Get version
+        id: version
+        run: |
+          echo "::set-output name=tweak::$(date +'%Y%m%d%H%M')"
+
+  build:
+    name: Build
+    # TODO: this should be a self-hosted runner
+    runs-on: ubuntu-latest
+    needs: version
     strategy:
       fail-fast: false
       matrix:
-        os: ${{ fromJson(inputs.os) }}
-        variant: ${{ fromJson(inputs.variant) }}
+        os: [ubuntu18.04, ubuntu20.04, debian9]
+        variant: [
+            { arch: arm, platform: linux/arm/v7 },
+            { arch: arm64, platform: linux/arm64/v8 },
+            { arch: amd64, platform: linux/amd64 },
+          ]
     env:
       container-workspace: /azure-osconfig
+
     steps:
-      - uses: actions/checkout@v3
-        with:
-          submodules: recursive
-          clean: true
+      - run: echo "Build package..."
+      # - uses: actions/checkout@v3
+      #   with:
+      #     submodules: recursive
+      #     clean: true
 
-      - name: Set version
-        id: version
-        run: echo "::set-output name=tweak::$(echo $(date +'%Y%m%d%H%M'))"
+      # - name: Run container
+      #   id: container
+      #   uses: ./.github/actions/container-run
+      #   with:
+      #     username: ${{ secrets.ACR_CLIENT_ID }}
+      #     password: ${{ secrets.ACR_CLIENT_SECRET }}
+      #     os: ${{ matrix.os }}
+      #     arch: ${{ matrix.variant.arch }}
+      #     platform: ${{ matrix.variant.platform }}
+      #     mount: ${{ github.workspace }}:${{ env.container-workspace }}
 
-      - name: Run container
-        id: container
-        uses: ./.github/actions/container-run
-        with:
-          username: ${{ secrets.ACR_CLIENT_ID }}
-          password: ${{ secrets.ACR_CLIENT_SECRET }}
-          os: ${{ matrix.os }}
-          arch: ${{ matrix.variant.arch }}
-          platform: ${{ matrix.variant.platform }}
-          mount: ${{ github.workspace }}:${{ env.container-workspace }}
+      # - name: Generate build
+      #   uses: ./.github/actions/container-exec
+      #   with:
+      #     container: ${{ steps.container.outputs.id }}
+      #     cmd: |
+      #       mkdir build && cd build
+      #       cmake ../src -DCMAKE_BUILD_TYPE=${{ env.build-type }} -DTWEAK_VERSION=${{ needs.version.outputs.tweak }} -Duse_prov_client=ON -Dhsm_type_symm_key=ON -DCOMPILE_WITH_STRICTNESS=ON -DBUILD_TESTS=OFF -DBUILD_SAMPLES=OFF -DBUILD_AGENTS=ON -G Ninja
 
-      - name: Generate build
-        uses: ./.github/actions/container-exec
-        with:
-          container: ${{ steps.container.outputs.id }}
-          cmd: |
-            mkdir build && cd build
-            cmake ../src -DCMAKE_BUILD_TYPE=${{ inputs.build-type }} -DTWEAK_VERSION=${{ steps.version.outputs.tweak }} -Duse_prov_client=ON -Dhsm_type_symm_key=ON -DCOMPILE_WITH_STRICTNESS=ON -DBUILD_TESTS=OFF -DBUILD_SAMPLES=OFF -DBUILD_AGENTS=ON -G Ninja
+      # - name: Build azure-osconfig
+      #   uses: ./.github/actions/container-exec
+      #   with:
+      #     container: ${{ steps.container.outputs.id }}
+      #     working-directory: ${{ env.container-workspace }}/build
+      #     cmd: cmake --build . --config ${{ env.build-type }}
 
-      - name: Build azure-osconfig
-        uses: ./.github/actions/container-exec
-        with:
-          container: ${{ steps.container.outputs.id }}
-          working-directory: ${{ env.container-workspace }}/build
-          cmd: cmake --build . --config ${{ inputs.build-type }}
+      # - name: Run cpack
+      #   uses: ./.github/actions/container-exec
+      #   with:
+      #     container: ${{ steps.container.outputs.id }}
+      #     working-directory: ${{ env.container-workspace }}/build
+      #     cmd: cpack -G DEB
 
-      - name: Run cpack
-        uses: ./.github/actions/container-exec
-        with:
-          container: ${{ steps.container.outputs.id }}
-          working-directory: ${{ env.container-workspace }}/build
-          cmd: cpack -G DEB
+      # - uses: actions/upload-artifact@v2
+      #   with:
+      #     name: ${{ env.artifact }}
+      #     path: ./build/osconfig_*
 
-      - name: Binary footprint delta validation
-        uses: ./.github/actions/footprint-check
-        with:
-          allowedDelta: 10
-          distroName: ${{ matrix.os }}
-          arch: ${{ matrix.variant.arch }}
-
-      - uses: actions/upload-artifact@v2
-        with:
-          name: ${{ inputs.artifact }}
-          path: ./build/osconfig_*
-
-  signing:
-    name: Signing
-    runs-on: [self-hosted, 1ES.Pool=azure-osconfig-windows-pool]
-    if: inputs.signed
-    needs: [package]
-    environment: esrp
+  validate:
+    name: Validate
+    runs-on: ubuntu-latest
+    needs: [build, version]
+    env:
+      report: package-report
+      package-sizes: package-sizes.json
     steps:
       - uses: actions/checkout@v3
 
-      - uses: actions/download-artifact@v3
+      - name: Download previous report
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          mkdir ./previous && cd ./previous
+          run=$(echo ${{ github.run_number }} - 1 | bc)
+          gh run download -n package-report-$run
+          exit 0
+
+      # TODO: ignore failures from previous download step (and remove always() from subsequent steps)
+
+      - uses: actions/download-artifact@v2
+        if: always()
         with:
-          name: ${{ inputs.artifact }}
-          path: ${{ github.workspace }}/osconfig_bin
+          name: ${{ env.artifact }}
+          path: ./packages
 
-      - name: Install ESRPClient
+      - name: List package sizes
+        if: always()
+        id: current
         run: |
-          az storage blob download -f esrpclient.zip -c esrpclient -n esrpclient.zip --connection-string "${{ secrets.BLOB_STORAGE_CONNECTION_STRING }}"
-          Expand-Archive esrpclient.zip
+          output="footprint.json"
 
-      - name: Stage artifacts for signing
-        working-directory: ${{ github.workspace }}/osconfig_bin
-        run: Get-ChildItem -Recurse -File -Filter *.deb | Move-Item -Destination ${{ github.workspace }}/esrpclient/Input
+          find ./packages/*.deb |
+          while read package; do
+            name=$(basename $package)
 
-      - name: Download certificates
-        run: |
-          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
-          az keyvault secret download --file certAAD.pfx --encoding base64 --name ${{ secrets.AAD_CERTIFICATE }} --vault-name ${{ secrets.KEY_VAULT }}
-          az keyvault secret download --file certESRP.pfx --encoding base64 --name ${{ secrets.ESRP_CERTIFICATE }} --vault-name ${{ secrets.KEY_VAULT }}
+            # Get the distro and architecture from the package name
+            distro=$(echo $name | cut -d_ -f3)
+            arch=$(echo $name | cut -d_ -f4-5)
 
-      - name: Import certificates
-        run: |
-          Set-Location -Path cert:\CurrentUser\My
-          Import-PfxCertificate -FilePath ${{ github.workspace }}\certAAD.pfx
-          Import-PfxCertificate -FilePath ${{ github.workspace }}\certESRP.pfx
+            case $distro in
+              ("bionic")  distro="ubuntu-18.04";;
+              ("focal")   distro="ubuntu-20.04";;
+              ("stretch") distro="debian-9";;
+            esac
 
-      - name: Sign packages
-        working-directory: ${{ github.workspace }}/esrpclient
-        run: |
-          mkdir Output
-          ${{ github.workspace }}\devops\scripts\create_esrp_job.ps1 (ls .\Input\ | select -expand Name) ($pwd.Path + '\Input') ($pwd.Path + '\Output')
-          cat Job.json
-          .\EsrpClient.exe Sign -a "Config\Auth.json" -c "Config\Config.json" -i "Job.json" -o "Output\output.json" -p "Config\Policy.json" -l Verbose
+            case $arch in
+              ("x86_64")  arch="amd64";;
+              ("aarch64") arch="arm64";;
+              ("armv7l")  arch="arm";;
+            esac
 
-      - name: Validate ESRP signing
-        working-directory: ${{ github.workspace }}/esrpclient
-        run: |
-          $result = (((cat .\Output\output.json | ConvertFrom-Json).submissionResponses | where { $_.statusCode -eq "pass" }).statusCode).Count -eq (ls .\Input\).Count
-          if ($result -eq $false)
-          {
-            Write-Error "Failed signing" -TargetObject $result
-          }
+            # Get the size of the package
+            size=$(ls -l $package | awk '{print $5}')
+
+            # Create the package JSON object
+            jq -n --arg target "$distro-$arch" --arg size "$size" '{"target": $target, "size": $size | tonumber}'
+          done | jq -s '.' > "$output"
+
+          echo ::set-output name=sizes::"$output"
 
       - uses: actions/upload-artifact@v2
+        if: always()
         with:
-          name: ${{ inputs.artifact }}-signed
-          path: ${{ github.workspace }}/esrpclient/Output/
+          name: package-report-${{ github.run_number }}
+          path: ./${{ steps.current.outputs.sizes }}
+
+      - name: Generate report
+        if: always()
+        id: report
+        run: |
+          current=${{ steps.current.outputs.sizes }}
+          previous=./previous/footprint.json
+
+          report=report.md
+
+          failures=0
+
+          # Set the header of the report table
+          echo "| Target | Current (*bytes*) | Previous (*bytes*) | Delta (*bytes*) |" > $report
+          echo "| --- | --- | --- | --- |" >> $report
+
+          for package in $(jq -c '.[]' $current); do
+            target=$(echo "$package" | jq -r '.target')
+            version=$(echo "$package" | jq -r '.version')
+            curr_size=$(echo "$package" | jq -r '.size')
+
+            if [[ $(jq -c --arg target "$target" '.[] | select(.target == $target)' $previous) ]]; then
+              prev_size=$(jq -r --arg target "$target" '.[] | select(.target == $target) | .size' $previous)
+              delta=$(($curr_size - $prev_size))
+
+              if [[ $delta -gt 0 ]]; then
+                  delta="+$delta"
+              elif [[ $delta -lt 0 ]]; then
+                  delta="-$delta"
+              fi
+
+              # Check if the delta is within the threshold
+              percent=$(echo "scale=2; $delta / $prev_size * 100" | bc)
+              if [[ $percent -gt ${{ env.threshold }} ]]; then
+                  delta="**$delta** :x:"
+                  echo ::error file=$package,title="Package delta threshold exceeded" "Package $target increased by $percent% ($delta bytes)"
+                  failures=$((failures + 1))
+              fi
+
+              echo "| $target | $curr_size | $prev_size | $delta |" >> $report
+            else
+              echo ::warning file=$target,title="New/missing package artifact" "'$target' is new or missing from the previous build."
+            fi
+          done
+
+          echo ::set-output name=markdown::"$report"
+
+          if [[ $failures -gt 0 ]]; then
+              exit 1
+          fi
+
+      - uses: actions/upload-artifact@v2
+        if: always()
+        with:
+          name: ${{ env.report }}
+          path: ${{ steps.report.outputs.markdown }}
+
+      - name: Create report
+        uses: ./.github/actions/check-run
+        with:
+          name: Package report
+          # TODO: use the full version string in this title
+          title: Footprint (${{ needs.version.outputs.tweak }})
+          markdown: ${{ steps.report.outputs.markdown }}
